/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_firstndk_firstjni_JniTest */

#ifndef _Included_com_example_firstndk_firstjni_JniTest
#define _Included_com_example_firstndk_firstjni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_firstndk_firstjni_JniTest
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_firstndk_firstjni_JniTest_getJniString
        (JNIEnv *env, jclass object){
    return (*env)->NewStringUTF(env,"important key is created in 2023.09.13 16.59");
};

#ifdef __cplusplus
}
#endif
#endif
