/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_firstndk_firstjni_JniTestOne */

#ifndef _Included_com_example_firstndk_firstjni_JniTestOne
#define _Included_com_example_firstndk_firstjni_JniTestOne
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_firstndk_firstjni_JniTestOne
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_firstndk_firstjni_JniTestOne_getJniString
  (JNIEnv *env, jclass){
      return (*env)->NewStringUTF(env,"important key str!!!");
  }

#ifdef __cplusplus
}
#endif
#endif
